<?php $_cartQty = $this->getSummaryCount() ?>
<div class="cart-dropdown">

<?php if($_cartQty > 0) : // make sure we have a positive amount first ?>
    <?php if ($_cartQty == 1) : // if we have ONE ?>
        <a href="<?php echo $this->getUrl('checkout/cart'); ?>" title="<?php echo $this->__('There is 1 item in your cart.') ?>">My Cart (1 item)</a>
    <?php elseif($_cartQty < 1) : // if we have MANY ?>
        <a href="<?php echo $this->getUrl('checkout/cart'); ?>" title="<?php echo $this->__('There are '. $_cartQty .' items in your cart.') ?>">My Cart (<?php echo $_cartQty ?> items)</a>
        <?php else : // if we have NONE ?>
        <a href="<?php echo $this->getUrl('checkout/cart'); ?>" title="<?php echo $this->__('There are no items in your cart.') ?>">My Cart (empty)</a>
    <?php endif; ?>
<?php endif; ?>

<?php if ($this->getIsNeedToDisplaySideBar()) : // can we even display the sidebar? ?>
<div class="dropdown" style="display: none">
    <div class="block block-cart">
        <div class="block-title"><?php echo $this->__('My Cart') ?></div>
        <div class="block-content">
        <?php if ($_cartQty > 0) : ?>
            <div class="summary">
                <?php if ($_cartQty == 1) : ?>
                    <p class="amount"><?php echo $this->__('There is <a href="%s">1 item</a> in your cart.', $this->getUrl('checkout/cart')) ?></p>
                <?php else : ?>
                    <p class="amount"><?php echo $this->__('There are <a href="%s">%s items</a> in your cart.', $this->getUrl('checkout/cart'), $_cartQty) ?></p>
                <?php endif ?>
                <p class="subtotal">
                    <?php if ($this->canApplyMsrp()) : // can we apply MSRP? ?>
                        <span class="map-cart-sidebar-total"><?php echo $this->__('ORDER TOTAL WILL BE DISPLAYED BEFORE YOU SUBMIT THE ORDER'); ?></span>
                    <?php else : ?>
                        <span class="label"><?php echo $this->__('Cart Subtotal:') ?></span> <?php echo Mage::helper('checkout')->formatPrice($this->getSubtotal()) ?>
                        <?php if ($_subtotalInclTax = $this->getSubtotalInclTax()) : ?>
                            <br>(<?php echo Mage::helper('checkout')->formatPrice($_subtotalInclTax) ?> <?php echo Mage::helper('tax')->getIncExcText(true) ?>)
                        <?php endif; ?>
                    <?php endif; ?>
                </p>
            </div>
        <?php endif ?>
        <?php if($_cartQty && $this->isPossibleOnepageCheckout()) : ?>
        <div class="actions">
            <?php echo $this->getChildHtml('extra_actions') ?>
            <button type="button" title="<?php echo $this->__('Checkout') ?>" class="button" onclick="setLocation('<?php echo $this->getCheckoutUrl() ?>')"><span><span><?php echo $this->__('Checkout') ?></span></span></button>
        </div>
        <?php endif ?>
        <?php $_items = $this->getRecentItems() ?>
        <?php if(count($_items)) : ?>
            <p class="block-subtitle"><?php echo $this->__('Recently added item(s)') ?></p>
            <ol id="cart-sidebar" class="mini-products-list">
            <?php foreach($_items as $_item) : ?>
                <?php echo $this->getItemHtml($_item) ?>
            <?php endforeach; ?>
            </ol>
        <?php else : ?>
            <p class="empty"><?php echo $this->__('You have no items in your shopping cart.') ?></p>
        <?php endif ?>
        </div>
    </div>
</div>
<?php endif;?>
</div>