<?php
/**
 * This file contains the social media information that is available on
 * the product view page. Periodic releases of this theme will be released
 * as updates and this file MAY OR MAY NOT BE included in those files.
 * A list of affected files will come with any update in the future.
 *
 * @category    design
 * @package     default_your_company
 * @copyright   Copyright (c) 2012 AtomicPages LLC <http://www.atomicpages.net>
 * @license     GPL 3.0
 * @author		Dennis Thompson AtomicPages LLC <http://www.atomicpages.net>
 */
?>

<?php
	$_product = $this->getProduct();
	$_helper = $this->helper('catalog/output')
?>

<div class="social-sharing">
	<ul class="social-links">
		<li class="fb first"><div class="fb-like" data-href="<?php echo urlencode(Mage::helper('core/url')->getCurrentUrl()); ?>" data-send="false" data-width="0" data-show-faces"false" data-layout="box_count" colorscheme="light" action="like"></div></li>
		<li class="twitter"><a href="https://twitter.com/share" data-url="<?php echo urlencode(Mage::helper('core/url')->getCurrentUrl()); ?>" data-count="vertical" class="twitter-share-button">Tweet</a></li>
		<li class="google"><div class="g-plusone" data-size="tall" data-href="<?php echo urlencode(Mage::helper('core/url')->getCurrentUrl()); ?>"></div></li>
		<li class="pin last"><a href="http://pinterest.com/pin/create/button/?url=<?php echo urlencode(Mage::helper('core/url')->getCurrentUrl()) ?>&media=<?php echo urlencode($this->helper('catalog/image')->init($_product, 'image')->resize(265)) ?>&description=<?php echo urlencode($this->stripTags($this->getImageLabel($_product, 'small_image'), null, true)) ?>" class="pin-it-button" count-layout="vertical"><img border="0" src="//assets.pinterest.com/images/PinExt.png" title="Pin It"></a></li>
	</ul>
</div>